# Generated by Django 4.1.3 on 2022-11-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_alter_referencemedia_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencemedia',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
