# Generated by Django 4.2.7 on 2023-11-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(default='test', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(default='test', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.CharField(default='test', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
