# Generated by Django 4.2.7 on 2023-11-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_blogpost_slug_project_slug_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.ManyToManyField(blank=True, null=True, to='website.images'),
        ),
    ]
